### ISSUE TITLE
It's not really an issue but more of a question.

### ISSUE THREAD

**Issue by gaining** [dat1guy/plugin.video.unofficialkissanime#7]
Hello dat1guy.
I've been maintaining the highway99 kissanime addon in tvaddons repo since he hasn't been updating it to deal with the kissanime website recent changes. I'm just wondering if it's ok to use your decryption to fix the addon.  One more note, I do believe the best way to avoid decryption altogether is to somehow use beautifulsoup and request libraries to scan the kissanime webpage and get the embed video urls and process the links for kodi playback just like a web browser playing it. I myself haven't used those tools yet but I've been learning about them lately.

**Comment by dat1guy** [comment]
Hey!

UKAP is open source, so you can use whatever you want as long as you include the license.

Currently my attention is on getting a 9anime add-on off the ground, but you're right; the correct way to do things would be to handle them like a browser. In my eyes, there are 3 solutions to this problem: 1) parse and interpret the JavaScript that's doing the encryption using something like js2py, 2) port the JavaScript to Python and mirror the logic (currently what I'm doing) or 3) use a headless browser like selenium, which will execute the JavaScript and embed the link in the video player, which is what you're proposing, right? Correct me if you're talking about something else.

In theory, I would love to do option 2. However there are a few drawbacks that make me nervous:
- Including a headless browser with UKAP means including it's binaries, and there aren't many (or maybe even any?) that support all the different​ platforms that Kodi runs on, like Android or the Pi for instance. I absolutely don't want to shut out users that are on uncommon platforms, so I would need to find something that's truly multi platform. I haven't looked terribly hard, but I don't know of anything that fits the bill. In fact, the Kodi devs on the forums often recommended porting the JS code to Python over using a headless browser, because of this pain!

- If we did find a headless browser that's acceptable, we would have to access a separate page for each quality, eg once for 1080p, once for 720p, etc. For websites that are fast, this wouldn't be that big of a deal, but the KissAnime site isnt super speedy.
- Adding a headless browser is currently a lot more work than options 1 and 2, although it's obviously the best solution in terms of correctness.

Those are the main issues I have with that strategy. If you know of a good one though, I'm willing to take a look at it.

**Comment by gaining** [comment]
Thanks, and I'm not sure if it's really a headless browser I was talking about. More like web-scraping the kissanime website for the video links and just play them as they are maybe a headless browser is a way to do that, maybe I could come up with something else. I'm fairly new to the whole kodi addon dev thing as my experiences are with python and pyqt. 
With option 2, porting JavaScript to python. I know that python has JavaScript support but maybe kodi python doesn't and that's why you're doing it? That also means you'll have do deal with decryption again once the kiss website changes its encryption algorithms? I still think something like option 3 is the best in terms of maintainability although, as you say, it is a lot of work but I believe will pay off in the end.

**Comment by dat1guy** [comment]
I'm not sure what you're talking about then.  Do you mean when you load the page, get the url that's embedded in the page?  I actually already do that as a fallback if I can't get the video links for each quality if, for example, I can't decrypt those video links.  Is that what you mean?

**Comment by dat1guy** [comment]
RE: JavaScript in Python, yeah, Kodi's python doesn't have built-in support for JavaScript.  I can bundle in a third party module like [js2py](https://github.com/PiotrDabkowski/Js2Py) with my add-on, and that's the best I can do.  Unfortunately, even js2py cannot evaluate some of the JavaScript used by the site.  For example, it fails on the unescape built-in function in Scripts/css.js.  So it looks like option 1 is dead in the water.

Also, annoyingly enough, the raw html for the site no longer has a video link embedded in the video html element; it's now dynamically written there by some JavaScript.

AFAIK, there is no built-in way to read html that's dynamically generated/modified in Python, which is why I keep referring headless browsers, which read the HTML after the JavaScript has been run.

**Comment by gaining** [comment]
After experimenting with selenium today and also ghost.py I fully understand your point of view and I'm sorry to have confused you. A headless web client would be the perfect solution for our problem with these addons if we were only going support one platform. I realized supporting it for other platforms is going to be a pain. And yes, you were on point.
